-- INSERT INTO bbox_prompts
-- (game_id, prompt, prompt_type)
-- VALUES
-- (1, 'Convince yourself that you have the power to ____.', 'MPOne'),
-- (1, 'You can’t go back and change the beginning, but you can start where you are and ____.', 'MPOne'),
-- (1, 'Happiness is not ____, it''s ____.','MPTwo'),
-- (1, 'You miss 100% of the ____ that you don''t ____.', 'MPTwo'),
-- (1, 'The most precious gift we can offer others is ____.', 'MPOne'),
-- (1, 'If you are not willing to ____, no one can help you. If you are determined to ____, no one can stop you.', 'MPTwo'),
-- (1, 'Be patient. ____ are not ____ in a day.', 'MPTwo'),
-- (1, 'Never perceive anything as ____. The only absolute is ____', 'MPTwo'),
-- (1, 'Remember, ____ is a fruit in season at all time and within reach of every ____.', 'MPTwo'),
-- (1, 'The truest indication of gratitude is ____.', 'MPOne'),
-- (1, 'There’s no need to rush. What’s meant for you always ____.', 'MPOne'),
-- (1, 'Happiness lies in the joy of ____ and the thrill of ____.', 'MPTwo'),
-- (1, 'Find ____ in your own heart so that you may find ____ in every Heart!', 'MPTwo'),
-- (1, 'For everything you have lost, you have gained ____.', 'MPOne'),
-- (1, 'Doing what you like is freedom. Liking what you do is ____.', 'MPOne'),
-- (1, 'The universe will often give you ____, even when you didn''t realize it was what you were truly wanting.', 'MPOne'),
-- (1, 'We have a ''strategic'' plan. It''s called ____.', 'MPOne'),
-- (1, 'Your future is created by ____, not ____.', 'MPTwo'),
-- (1, 'The happiest people don''t have ____, they make ____.', 'MPTwo'),
-- (1, 'In life, you''ll meet two kinds of people. The ones who ____ and the ones who ____. In the end, you''ll thank them both.', 'MPTwo'),
-- (1, 'I thank all those who laughed at my ____; you taught me to ____.', 'MPTwo');